// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCYIOILQv-ZNqkx9snUYduhwwvcvING2Nc',
    appId: '1:583230285850:web:3a0fb86b2c890809b5c9a3',
    messagingSenderId: '583230285850',
    projectId: 'idance-f47da',
    authDomain: 'idance-f47da.firebaseapp.com',
    storageBucket: 'idance-f47da.appspot.com',
    measurementId: 'G-Y5PM2HVTZ2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBzNG8Sb2VmJPTdNrHX0dNWF7lwCR8xWKI',
    appId: '1:583230285850:android:2151844d92d298c2b5c9a3',
    messagingSenderId: '583230285850',
    projectId: 'idance-f47da',
    storageBucket: 'idance-f47da.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBvaJZQcMHfOODQr4sZPEGkr8KK7__VxPs',
    appId: '1:583230285850:ios:396151ea63237c0ab5c9a3',
    messagingSenderId: '583230285850',
    projectId: 'idance-f47da',
    storageBucket: 'idance-f47da.appspot.com',
    iosClientId: '583230285850-phsvi8vbf7rj49oeuc49e8fud1v3vorg.apps.googleusercontent.com',
    iosBundleId: 'com.example.iDance',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBvaJZQcMHfOODQr4sZPEGkr8KK7__VxPs',
    appId: '1:583230285850:ios:396151ea63237c0ab5c9a3',
    messagingSenderId: '583230285850',
    projectId: 'idance-f47da',
    storageBucket: 'idance-f47da.appspot.com',
    iosClientId: '583230285850-phsvi8vbf7rj49oeuc49e8fud1v3vorg.apps.googleusercontent.com',
    iosBundleId: 'com.example.iDance',
  );
}
